server {
    listen 80;
    server_name crm.mechlintech.com;

    location / {
        proxy_pass http://login-whitelabel-prod:3010;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}